name: Bug report
description: Report a problem or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
  - type: input
    id: version
    attributes:
      label: Extension version
      description: What version are you using?
      placeholder: e.g., 1.2.3
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Edge
        - Brave
        - Other (please specify below)
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g., macOS 14.2, Windows 11, Ubuntu 24.04
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear, ordered steps so we can reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happens?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console logs / screenshots
      description: Paste any relevant logs or attach screenshots.
      render: shell
    validations:
      required: false
